server:
  port: 8080

spring:
  application:
    name: movieBooking

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update